name: cn.mops CI

on: [push, pull_request]

jobs:
  run-cnv-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Cache Docker layers
          uses: actions/cache@v3
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

        - name: Build Docker image
          run: |
            docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t cnmops-docker .

        - name: Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}/cnv/test:/workdir/cnv/test cnmops-docker pytest /workdir/cnv/test

        - name: Upload Test Results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: cnv/test/.pytest_cache
