name: cn.mops CI

on: [pull_request]

jobs:
  run-cnv-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            driver-opts: image=moby/buildkit:latest

#        - name: Cache Docker layers
#          uses: actions/cache@v3
#          with:
#            path: /tmp/.buildx-cache
#            key: ${{ runner.os }}-buildx-${{ github.sha }}
#            restore-keys: |
#              ${{ runner.os }}-buildx-

        - name: Build docker
          uses: docker/build-push-action@v4
          with:
            context: .
            provenance: false
            load: true
            push: false
            tags: cnmops-docker
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}/cnv/test:/workdir/cnv/test cnmops-docker pytest /workdir/cnv/test

        - name: Upload Test Results
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: cnv/test/.pytest_cache
